### ISSUE TITLE
IMG references have an extra /images/ in the URL

### ISSUE THREAD

**Issue by n2ygk** [lmmx/gdocs2md-html#1]
When rendering a gdoc with embedded images, the created Google Drive folder structure is:
```
Markdown/<docname>.md
Markdown/<docname>_images/image_0.png
...
```
but the image refs in `<docname>.md` are of the form:

```
![](/images/<docname>_images/image_0.png)
```

With an extra ***/images/*** prefix. Workaround is just to make an `images` folder (after downloading and unzipping the gdrive Markdown folder) and moving the `<docname>_images` into it.

Happy to fix myself and submit a pull request if that will help. Will take me a bit of time to figure out how;-)

Thanks for this cool tool.

**Comment by lmmx** [comment]
Hey Alan, sorry it's taken a while to get back to you!

I don't use the locally saved images myself, but it's a simple fix. The bit to change is `script_properties.setProperty("image_folder_prefix", "/images/");` for the record, I'll do it now.

The way I'm currently using it is with the "View as Markdown" button/popup: I upload an image to my hosting site, copy + paste it into the Doc, click the image and set a link (Ctrl/Cmd + K) to the source URL for the image, and the "View as markdown" button then overrides that local image saving. Otherwise I probably would have noticed this, oops

**Comment by n2ygk** [comment]
Nope. Just make the image_folder_prefix empty and then you'll have it. I
made this change and tested. If you'd like me to fork and submit a pull
request, let me know. Thanks for the quick turnaround!
/a

**Comment by lmmx** [comment]
OK brilliant, thanks for your help :+1:
