### ISSUE TITLE
export -> markdown/view in browser missing

### ISSUE THREAD

**Issue by n2ygk** [lmmx/gdocs2md-html#2]
The README shows a submenu of export -> markdown called "view in browser" but that is not in the code on the master branch. Is there a branch you've perhaps neglected to push to github and/or merge into master?

Thanks.

**Comment by lmmx** [comment]
Woops sorry for the delay here! No, I've not "published" to the Chrome add-on er.. marketplace, or whatever it is you publish to, so I've just been copying and pasting [the exportmd.gs file](https://github.com/lmmx/gdocs2md-html/blob/master/exportmd.gs) contents straight off GitHub into the Script Editor then installing (what you see there is what I've used)

Yeah I rejigged the script since it was the only feature I was using for the time being, it's now the top-level `Markdown > View as markdown` option :smile: Sorry for any confusion!
